#!/usr/bin/env bash
# A Script that shows information about subdomains

# function that gets the DNS information
dns () {
	domain=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $domain" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
	# calling the function when only the domain is provided
	dns "$1" "www"
	dns "$1" "lb-01"
	dns "$1" "web-01"
	dns "$1" "web-02"
elif [ "$#" == 2 ]
then
	dns "$1" "$2"
fi
