#!/usr/bin/env bash
# Installing nginx on server

sudo apt update
sudo apt -y nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx start'
