#!/usr/bin/env bash
# The bash script that installs nginx with certain requirememts

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart

