#!/usr/bin/env bash
# This script redirects the server to another page

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
text="server {
		listen 80 default_server;
        	listen [::]:80 default_server;

		root /var/www/html;

		server_name lavictoire.tech;

		location / {
				try_files $uri $uri/ =404;
			}

		location = /redirect_me {
				return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
			}
	}"
bash -c "echo -e '$text' > /etc/nginx/sites-enabled/default"
sudo service nginx restart
