#!/usr/bin/env bash
# Configuring a new machine that redirects to another page

# installing nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# making the home page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# configuring nginx for redirection
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default

# making the error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error.html

# configuring nginx to load the page on error
string="listen 80 default_server;\n\terror_page 404 \/error.html;\n\tlocation = \/error.html {\n\t\troot \/var\/www\/html;\n\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
