#!/usr/bin/env bash
# This script configures a new machine to redirect permanently to another page

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx start
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/error.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/error.html;\n\tlocation = \/error.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo sed -i "/server {/a \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx restart
