#!/usr/bin/env bash
# Configures a new machine to be act as a load balancer btw two servers

# installing HAProxy
sudo apt-get update
sudo apt-get -y install haproxy

# configuring HAProxy to receive traffic from 2 servers
server=\
"
	listen load_balancer
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
        server 144516-web-01 3.90.70.134:80 check
        server 144516-web-02 54.157.130.35:80 check
"
echo "$server" | sudo tee -a /etc/haproxy/haproxy.cfg

# configuring haproxy to work with an init file
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# restarting haproxy to confirm the changes
sudo service haproxy restart
