#!/usr/bin/env bash
# Configures a new machine to be act as a load balancer btw two servers

# installing HAProxy
sudo apt-get update
sudo apt-get -y install haproxy

# configuring HAProxy to receive traffic from 2 servers
server=\
"
frontend  the_front
        bind *:80
        mode http
        default_backend the_back
backend the_back
        balance roundrobin
        server 144516-web-01 100.25.109.44:80 check
        server 144516-web-02 34.239.248.185:80 check
"
echo "$server" | sudo tee /etc/haproxy/haproxy.cfg

# configuring haproxy to work with an init file
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# restarting haproxy to confirm the changes
sudo service haproxy restart
