#!/usr/bin/env bash
# This script does the following;
# Creates a file with its PID
# Displaays something indefinitely
# Displays sth when it receives a SIGTERM command
# And so on...

echo "$$" > /var/run/myscript.pid

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT
while true; do
	echo "To infinity and beyond"
done
