#!/usr/bin/env bash
# This script displays something indefinitely
# It also displas something else wheit receives a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM
while true; do
	echo "To infinity and beyond"
	sleep 2
done
