#!/usr/bin/env bash
# This script prints "Best School" 10x with some modif on the 9th line

num=1

while [ $num -le 10 ]; do
	echo "Best School"
	if [ $num -eq 9 ]; then
		echo "Hi"
	fi
	((num++))
done
