#!/usr/bin/env bash
# This script changes the hostname IP address
# It also changes Facebook's IP address too
# How? We just modify the /etc/hosts file

cp /etc/hosts /etc/new_hosts
# Overwriting localhost
echo "127.0.0.2		localhost" > /etc/new_hosts
# Appending the facebook IP address
echo "8.8.8.8		facebook.com" >> /etc/new_hosts

cp -f /etc/new_hosts /etc/hosts
